"""Central controlled vocabulary and deterministic phrase aliases for GameGenie AI."""

from __future__ import annotations

from types import MappingProxyType
from typing import Final

TAXONOMY: Final = MappingProxyType(
    {
        "genres": (
            "action",
            "adventure",
            "role-playing",
            "first-person shooter",
            "third-person shooter",
            "strategy",
            "simulation",
            "puzzle",
            "racing",
            "sports",
            "platformer",
            "horror",
            "survival",
            "battle royale",
            "fighting",
            "stealth",
            "educational",
            "rhythm",
            "sandbox",
            "casual",
            "exploration",
            "music",
        ),
        "platforms": ("PC", "PlayStation", "Xbox", "Nintendo Switch", "Android", "iOS", "macOS", "Linux"),
        "modes": ("single-player", "multiplayer", "cooperative", "competitive", "online", "offline"),
        "themes": (
            "fantasy",
            "science-fiction",
            "cyberpunk",
            "space",
            "medieval",
            "post-apocalyptic",
            "historical",
            "military",
            "futuristic",
            "farming",
            "zombies",
            "mythology",
            "detective",
            "educational",
            "family-friendly",
            "nature",
            "mystery",
        ),
        "moods": (
            "relaxing",
            "intense",
            "dark",
            "cheerful",
            "atmospheric",
            "scary",
            "emotional",
            "humorous",
            "competitive",
            "adventurous",
        ),
        "visual_styles": ("realistic", "pixel-art", "2D", "3D", "cartoon", "retro"),
        "difficulty": ("easy", "medium", "hard"),
        "hardware_level": ("low-end", "mid-range", "high-end"),
        "price_type": ("free", "paid"),
    }
)

# Values intentionally repeat across aliases. Matching is longest-phrase-first in prompt_normalizer.
_ALIASES = {
    # genres and common terminology
    "action game": "action",
    "action games": "action",
    "adventure game": "adventure",
    "adventure games": "adventure",
    "rpg": "role-playing",
    "role playing": "role-playing",
    "roleplaying": "role-playing",
    "role-playing game": "role-playing",
    "role playing game": "role-playing",
    "fps": "first-person shooter",
    "first person shooter": "first-person shooter",
    "first-person shooting": "first-person shooter",
    "first person shooting": "first-person shooter",
    "shooter": "first-person shooter",
    "shooting game": "first-person shooter",
    "gun game": "first-person shooter",
    "tps": "third-person shooter",
    "third person shooter": "third-person shooter",
    "third-person shooting": "third-person shooter",
    "strategy game": "strategy",
    "tactical game": "strategy",
    "rts": "strategy",
    "real time strategy": "strategy",
    "turn based strategy": "strategy",
    "sim": "simulation",
    "simulation game": "simulation",
    "brain game": "puzzle",
    "puzzler": "puzzle",
    "logic game": "puzzle",
    "car game": "racing",
    "driving game": "racing",
    "race game": "racing",
    "football game": "sports",
    "sports game": "sports",
    "platform game": "platformer",
    "platforming": "platformer",
    "scary game": "horror",
    "horror game": "horror",
    "survival game": "survival",
    "battle-royale": "battle royale",
    "br game": "battle royale",
    "fighter": "fighting",
    "fighting game": "fighting",
    "sneaking game": "stealth",
    "learning game": "educational",
    "rhythm game": "rhythm",
    "music game": "rhythm",
    "open world": "sandbox",
    "open-world": "sandbox",
    "casual game": "casual",
    "exploration game": "exploration",
    # platforms
    "windows pc": "PC",
    "windows computer": "PC",
    "computer": "PC",
    "desktop": "PC",
    "play station": "PlayStation",
    "playstation 4": "PlayStation",
    "playstation 5": "PlayStation",
    "ps4": "PlayStation",
    "ps5": "PlayStation",
    "xbox one": "Xbox",
    "xbox series x": "Xbox",
    "xbox series s": "Xbox",
    "series x": "Xbox",
    "series s": "Xbox",
    "switch": "Nintendo Switch",
    "nintendo": "Nintendo Switch",
    "mobile android": "Android",
    "android phone": "Android",
    "iphone": "iOS",
    "ipad": "iOS",
    "apple mobile": "iOS",
    "mac": "macOS",
    "mac os": "macOS",
    "ubuntu": "Linux",
    # modes and multiplayer phrases
    "co-op": "cooperative",
    "coop": "cooperative",
    "co op": "cooperative",
    "play together": "cooperative",
    "team up": "cooperative",
    "play with friends": "multiplayer",
    "with friends": "multiplayer",
    "battle with team": "multiplayer cooperative",
    "team based": "cooperative",
    "team-based": "cooperative",
    "multi player": "multiplayer",
    "solo": "single-player",
    "single player": "single-player",
    "singleplayer": "single-player",
    "one player": "single-player",
    "versus": "competitive",
    "pvp": "competitive",
    "player versus player": "competitive",
    "online game": "online",
    "internet game": "online",
    "offline game": "offline",
    "without internet": "offline",
    "no internet": "offline",
    # themes and moods
    "sci fi": "science-fiction",
    "sci-fi": "science-fiction",
    "science fiction": "science-fiction",
    "space game": "space",
    "outer space": "space",
    "future setting": "futuristic",
    "future world": "futuristic",
    "farm game": "farming",
    "farming game": "farming",
    "zombie": "zombies",
    "zombie game": "zombies",
    "mythological": "mythology",
    "crime solving": "detective",
    "child friendly": "family-friendly",
    "child-friendly": "family-friendly",
    "kid friendly": "family-friendly",
    "kids game": "family-friendly",
    "family friendly": "family-friendly",
    "chill": "relaxing",
    "calm": "relaxing",
    "peaceful": "relaxing",
    "laid back": "relaxing",
    "high intensity": "intense",
    "thrilling": "intense",
    "spooky": "scary",
    "frightening": "scary",
    "funny": "humorous",
    "comedy": "humorous",
    "feel good": "cheerful",
    "story rich": "emotional",
    # visuals
    "pixel art": "pixel-art",
    "pixelated": "pixel-art",
    "two dimensional": "2D",
    "two-dimensional": "2D",
    "2 d": "2D",
    "three dimensional": "3D",
    "three-dimensional": "3D",
    "3 d": "3D",
    "cartoonish": "cartoon",
    "old school": "retro",
    "old-school": "retro",
    "lifelike": "realistic",
    # difficulty, hardware, and price
    "beginner friendly": "easy",
    "beginner-friendly": "easy",
    "simple": "easy",
    "normal difficulty": "medium",
    "moderate difficulty": "medium",
    "difficult": "hard",
    "challenging": "hard",
    "very hard": "hard",
    "low spec": "low-end",
    "low-spec": "low-end",
    "low end": "low-end",
    "low-end pc": "low-end PC",
    "potato pc": "low-end PC",
    "basic pc": "low-end PC",
    "budget pc": "low-end PC",
    "medium spec": "mid-range",
    "mid range": "mid-range",
    "high spec": "high-end",
    "high end": "high-end",
    "gaming rig": "high-end",
    "extreme hardware": "high-end",
    "no cost": "free",
    "free of cost": "free",
    "free to play": "free",
    "free-to-play": "free",
    "f2p": "free",
    "without paying": "free",
    "costs money": "paid",
    "premium game": "paid",
}

for _category_values in TAXONOMY.values():
    for _canonical in _category_values:
        _ALIASES.setdefault(_canonical.casefold(), _canonical)

SYNONYMS: Final = MappingProxyType(dict(sorted(_ALIASES.items())))
CATEGORY_BY_VALUE: Final = MappingProxyType(
    {value.casefold(): category for category, values in TAXONOMY.items() for value in values}
)


def is_canonical(category: str, value: str) -> bool:
    """Return whether *value* is a controlled value in *category*."""
    return category in TAXONOMY and value in TAXONOMY[category]


def category_for(value: str) -> str | None:
    """Resolve a canonical taxonomy value to its category."""
    return CATEGORY_BY_VALUE.get(value.casefold())


def taxonomy_counts() -> dict[str, int]:
    return {category: len(values) for category, values in TAXONOMY.items()}
